services:
  # Ethereum block scheduler application
  ethereum-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: ethereum-scheduler-app
    restart: always
    environment:
      # MongoDB Configuration - Connect to external MongoDB
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE:-crawler}
      MONGO_CONNECT_TIMEOUT: ${MONGO_CONNECT_TIMEOUT:-15s}
      MONGO_MAX_POOL_SIZE: ${MONGO_MAX_POOL_SIZE:-10}

      # Ethereum Configuration
      ETHEREUM_RPC_URL: ${ETHEREUM_RPC_URL:-https://mainnet.infura.io/v3/YOUR_PROJECT_ID}
      ETHEREUM_WS_URL: ${ETHEREUM_WS_URL:-wss://mainnet.infura.io/ws/v3/YOUR_PROJECT_ID}
      START_BLOCK_NUMBER: ${START_BLOCK_NUMBER:-latest}

      # Application Configuration
      APP_ENV: ${APP_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}

      # Crawler Configuration - Optimized for Infura free tier
      BATCH_SIZE: ${BATCH_SIZE:-1}
      CONCURRENT_WORKERS: ${CONCURRENT_WORKERS:-1}
      RETRY_ATTEMPTS: ${RETRY_ATTEMPTS:-3}
      RETRY_DELAY: ${RETRY_DELAY:-3s}

      # Batch Upsert Configuration - Enable duplicate handling
      CRAWLER_USE_UPSERT: ${CRAWLER_USE_UPSERT:-true}
      CRAWLER_UPSERT_FALLBACK: ${CRAWLER_UPSERT_FALLBACK:-true}

      # Rate limiting for Infura API
      ETHEREUM_RATE_LIMIT: ${ETHEREUM_RATE_LIMIT:-1s}
      ETHEREUM_REQUEST_TIMEOUT: ${ETHEREUM_REQUEST_TIMEOUT:-120s}
      ETHEREUM_SKIP_RECEIPTS: ${ETHEREUM_SKIP_RECEIPTS:-true}

      # Scheduler Configuration - Real-time mode
      SCHEDULER_MODE: ${SCHEDULER_MODE:-realtime}
      SCHEDULER_ENABLE_REALTIME: ${SCHEDULER_ENABLE_REALTIME:-true}
      SCHEDULER_ENABLE_POLLING: ${SCHEDULER_ENABLE_POLLING:-true}
      SCHEDULER_POLLING_INTERVAL: ${SCHEDULER_POLLING_INTERVAL:-3s}
      SCHEDULER_FALLBACK_TIMEOUT: ${SCHEDULER_FALLBACK_TIMEOUT:-30s}
      SCHEDULER_RECONNECT_ATTEMPTS: ${SCHEDULER_RECONNECT_ATTEMPTS:-5}
      SCHEDULER_RECONNECT_DELAY: ${SCHEDULER_RECONNECT_DELAY:-5s}

      # NATS JetStream Configuration (Disabled by default for scheduler)
      NATS_URL: ${NATS_URL:-nats://ethereum-nats:4222}
      NATS_STREAM_NAME: ${NATS_STREAM_NAME:-TRANSACTIONS}
      NATS_SUBJECT_PREFIX: ${NATS_SUBJECT_PREFIX:-transactions}
      NATS_CONNECT_TIMEOUT: ${NATS_CONNECT_TIMEOUT:-10s}
      NATS_RECONNECT_ATTEMPTS: ${NATS_RECONNECT_ATTEMPTS:-5}
      NATS_RECONNECT_DELAY: ${NATS_RECONNECT_DELAY:-2s}
      NATS_MAX_PENDING_MESSAGES: ${NATS_MAX_PENDING_MESSAGES:-1000}
      NATS_ENABLED: ${NATS_ENABLED:-false}

      # Monitoring Configuration
      METRICS_ENABLED: ${METRICS_ENABLED:-true}
      HEALTH_CHECK_INTERVAL: ${HEALTH_CHECK_INTERVAL:-30s}
    networks:
      - ethereum-scheduler-network
      - ethereum-network
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  ethereum-scheduler-network:
    driver: bridge
  ethereum-network:
    external: true
    name: ethereum-raw-data-crawler_ethereum-network
